server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/web_mib_browser?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
      encoding: utf-8
      schema-locations: classpath:init.sql

fast-crud:
  upload-dir: ${UPLOAD_DIR:${user.dir}/upload}