server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://${DB_IP:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:web_mib_browser}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASS:Admin&123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
      encoding: utf-8
      schema-locations: classpath:init.sql

logging:
  file:
    path: ${LOG_DIR:${user.dir}/logs}
    name: ${logging.file.path}/${LOG_FILE_NAME:web_mib_browser}.log

fast-crud:
  upload-dir: ${UPLOAD_DIR:${user.dir}/upload}

web-socket:
  path: /socket
  ssh-path: /webssh

task:
  connection-detect-freq: 60000 # 检测连接连通性的频率(ms)